# Minimal kitty config.
# Full commented reference: kitty.reference.conf

# Font
font_family      iosevka
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
disable_ligatures cursor

# Cursor
cursor_trail 1

# Scrollback
scrollback_lines 2000
scrollbar scrolled

# Mouse and selection
mouse_hide_wait 3.0
open_url_with default
detect_urls yes
show_hyperlink_targets no
underline_hyperlinks hover
copy_on_select yes
paste_actions quote-urls-at-prompt,confirm
strip_trailing_spaces smart
select_by_word_characters @-./_~?&=%+#
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+s  paste_from_selection

# Tabs and layouts
tab_bar_edge bottom
tab_bar_min_tabs 2
enabled_layouts tall,grid,stack,splits

# Mod key
kitty_mod alt

# Scrolling
map kitty_mod+u scroll_page_up
map kitty_mod+d scroll_page_down
map kitty_mod+backspace show_scrollback

# Window navigation
map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right

# Unmap default new_window command (pi uses this)
map kitty+enter
map kitty+shift+enter new_window

# Tabs
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+[ previous_tab
map kitty_mod+] next_tab
map kitty_mod+n new_tab
map kitty_mod+shift+t set_tab_title

# Layouts
map kitty_mod+space next_layout
map kitty_mod+shift+space last_used_layout
map kitty_mod+g goto_layout grid
map kitty_mod+t goto_layout tall
map kitty_mod+s goto_layout stack

# Resize windows
map kitty_mod+shift+h resize_window narrower 5
map kitty_mod+shift+j resize_window taller 5
map kitty_mod+shift+k resize_window shorter 5
map kitty_mod+shift+l resize_window wider 5

# Utilities
map kitty_mod+shift+u kitten unicode_input
map kitty_mod+f5 load_config_file

# Sound
enable_audio_bell no 
